ERROR - 2024-09-04 15:34:27 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\laragon\www\bibliothèque\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\laragon\www\bibliothèque\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\bibliothèque\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\bibliothèque\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\bibliothèque\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\bibliothèque\app\Controllers\Home.php(89): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\bibliothèque\system\CodeIgniter.php(933): App\Controllers\Home->AddClient()
#10 C:\laragon\www\bibliothèque\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\bibliothèque\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\bibliothèque\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\bibliothèque\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\bibliothèque\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\bibliothèque\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-09-04 15:34:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: AddClient]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:34:27 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:34:27\', \'2024-09-04 15:34:27\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:34:27\', \'2024-09-04 15:34:27\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:34:27 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:34:27\', \'2024-09-04 15:34:27\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:34:27\', \'2024-09-04 15:34:27\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:34:27\', \'2024-09-04 15:34:27\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
ERROR - 2024-09-04 15:34:57 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\laragon\www\bibliothèque\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\laragon\www\bibliothèque\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\bibliothèque\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\bibliothèque\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\bibliothèque\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\bibliothèque\app\Controllers\Home.php(89): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\bibliothèque\system\CodeIgniter.php(933): App\Controllers\Home->AddClient()
#10 C:\laragon\www\bibliothèque\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\bibliothèque\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\bibliothèque\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\bibliothèque\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\bibliothèque\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\bibliothèque\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-09-04 15:34:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: AddClient]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:34:57 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:34:57\', \'2024-09-04 15:34:57\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:34:57\', \'2024-09-04 15:34:57\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:34:57 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:34:57\', \'2024-09-04 15:34:57\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:34:57\', \'2024-09-04 15:34:57\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:34:57\', \'2024-09-04 15:34:57\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
ERROR - 2024-09-04 15:35:01 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\laragon\www\bibliothèque\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\laragon\www\bibliothèque\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\bibliothèque\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\bibliothèque\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\bibliothèque\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\bibliothèque\app\Controllers\Home.php(89): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\bibliothèque\system\CodeIgniter.php(933): App\Controllers\Home->AddClient()
#10 C:\laragon\www\bibliothèque\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\bibliothèque\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\bibliothèque\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\bibliothèque\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\bibliothèque\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\bibliothèque\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-09-04 15:35:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: AddClient]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:35:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:01\', \'2024-09-04 15:35:01\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:01\', \'2024-09-04 15:35:01\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:35:01 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:01\', \'2024-09-04 15:35:01\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:01\', \'2024-09-04 15:35:01\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:01\', \'2024-09-04 15:35:01\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
ERROR - 2024-09-04 15:35:05 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\laragon\www\bibliothèque\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\laragon\www\bibliothèque\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\bibliothèque\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\bibliothèque\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\bibliothèque\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\bibliothèque\app\Controllers\Home.php(89): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\bibliothèque\system\CodeIgniter.php(933): App\Controllers\Home->AddClient()
#10 C:\laragon\www\bibliothèque\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\bibliothèque\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\bibliothèque\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\bibliothèque\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\bibliothèque\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\bibliothèque\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-09-04 15:35:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: AddClient]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:35:05 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:05\', \'2024-09-04 15:35:05\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:05\', \'2024-09-04 15:35:05\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:35:05 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:05\', \'2024-09-04 15:35:05\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:05\', \'2024-09-04 15:35:05\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:05\', \'2024-09-04 15:35:05\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
ERROR - 2024-09-04 15:35:39 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\laragon\www\bibliothèque\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\laragon\www\bibliothèque\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\bibliothèque\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\bibliothèque\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\bibliothèque\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\bibliothèque\app\Controllers\Home.php(89): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\bibliothèque\system\CodeIgniter.php(933): App\Controllers\Home->AddClient()
#10 C:\laragon\www\bibliothèque\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\bibliothèque\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\bibliothèque\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\bibliothèque\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\bibliothèque\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\bibliothèque\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-09-04 15:35:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: AddClient]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:35:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:39\', \'2024-09-04 15:35:39\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:39\', \'2024-09-04 15:35:39\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:35:39 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:39\', \'2024-09-04 15:35:39\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:39\', \'2024-09-04 15:35:39\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:39\', \'2024-09-04 15:35:39\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
ERROR - 2024-09-04 15:35:43 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\laragon\www\bibliothèque\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\laragon\www\bibliothèque\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\bibliothèque\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\bibliothèque\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\bibliothèque\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\bibliothèque\app\Controllers\Home.php(89): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\bibliothèque\system\CodeIgniter.php(933): App\Controllers\Home->AddClient()
#10 C:\laragon\www\bibliothèque\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\bibliothèque\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\bibliothèque\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\bibliothèque\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\bibliothèque\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\bibliothèque\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-09-04 15:35:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: AddClient]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:35:43 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:43\', \'2024-09-04 15:35:43\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:43\', \'2024-09-04 15:35:43\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:35:43 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:43\', \'2024-09-04 15:35:43\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:43\', \'2024-09-04 15:35:43\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'0000000010\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:35:43\', \'2024-09-04 15:35:43\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Home.php(89): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
ERROR - 2024-09-04 15:44:08 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\laragon\www\bibliothèque\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\laragon\www\bibliothèque\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\bibliothèque\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\bibliothèque\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\bibliothèque\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\bibliothèque\app\Controllers\Home.php(85): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\bibliothèque\system\CodeIgniter.php(933): App\Controllers\Home->AddClient()
#10 C:\laragon\www\bibliothèque\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\bibliothèque\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\bibliothèque\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\bibliothèque\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\bibliothèque\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\bibliothèque\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-09-04 15:44:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: AddClient]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:44:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:44:08\', \'2024-09-04 15:44:08\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:44:08\', \'2024-09-04 15:44:08\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:44:08 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:44:08\', \'2024-09-04 15:44:08\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:44:08\', \'2024-09-04 15:44:08\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:44:08\', \'2024-09-04 15:44:08\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
ERROR - 2024-09-04 15:44:14 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\laragon\www\bibliothèque\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\laragon\www\bibliothèque\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\bibliothèque\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\bibliothèque\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\bibliothèque\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\bibliothèque\app\Controllers\Home.php(85): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\bibliothèque\system\CodeIgniter.php(933): App\Controllers\Home->AddClient()
#10 C:\laragon\www\bibliothèque\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\bibliothèque\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\bibliothèque\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\bibliothèque\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\bibliothèque\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\bibliothèque\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-09-04 15:44:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: AddClient]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:44:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:44:14\', \'2024-09-04 15:44:14\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:44:14\', \'2024-09-04 15:44:14\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:44:14 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:44:14\', \'2024-09-04 15:44:14\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:44:14\', \'2024-09-04 15:44:14\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:44:14\', \'2024-09-04 15:44:14\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
ERROR - 2024-09-04 15:46:38 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\laragon\www\bibliothèque\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\laragon\www\bibliothèque\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\bibliothèque\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\bibliothèque\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\bibliothèque\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\bibliothèque\app\Controllers\Home.php(85): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\bibliothèque\system\CodeIgniter.php(933): App\Controllers\Home->AddClient()
#10 C:\laragon\www\bibliothèque\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\bibliothèque\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\bibliothèque\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\bibliothèque\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\bibliothèque\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\bibliothèque\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-09-04 15:46:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: AddClient]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:46:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:46:38\', \'2024-09-04 15:46:38\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:46:38\', \'2024-09-04 15:46:38\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:46:38 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:46:38\', \'2024-09-04 15:46:38\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:46:38\', \'2024-09-04 15:46:38\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:46:38\', \'2024-09-04 15:46:38\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
ERROR - 2024-09-04 15:52:30 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\laragon\www\bibliothèque\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\laragon\www\bibliothèque\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\bibliothèque\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\bibliothèque\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\bibliothèque\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\bibliothèque\app\Controllers\Home.php(85): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\bibliothèque\system\CodeIgniter.php(933): App\Controllers\Home->AddClient()
#10 C:\laragon\www\bibliothèque\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\bibliothèque\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\bibliothèque\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\bibliothèque\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\bibliothèque\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\bibliothèque\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-09-04 15:52:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: AddClient]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:52:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:52:30\', \'2024-09-04 15:52:30\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:52:30\', \'2024-09-04 15:52:30\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 15:52:30 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:52:30\', \'2024-09-04 15:52:30\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:52:30\', \'2024-09-04 15:52:30\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'Harry Potter\', \'RAJAO\', \'Ambanivohitra\', \'0345588889899\', \'2024-09-04\', \'2024-09-04 15:52:30\', \'2024-09-04 15:52:30\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Home.php(85): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
ERROR - 2024-09-04 17:07:00 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\bibliothèque\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\laragon\www\bibliothèque\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\laragon\www\bibliothèque\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', Array, false)
#4 C:\laragon\www\bibliothèque\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\bibliothèque\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\bibliothèque\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\bibliothèque\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\bibliothèque\app\Controllers\Home.php(80): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\bibliothèque\system\CodeIgniter.php(933): App\Controllers\Home->AddClient()
#10 C:\laragon\www\bibliothèque\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\bibliothèque\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\bibliothèque\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\bibliothèque\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\bibliothèque\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\laragon\www\bibliothèque\system\rewrite.php(44): require_once('C:\\laragon\\www\\...')
#16 {main}
CRITICAL - 2024-09-04 17:07:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: AddClient]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(80): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 17:07:00 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'After chap II\', \'sds\', \'dsds\', \'dsd\', \'2024-09-04\', \'2024-09-04 17:07:00\', \'2024-09-04 17:07:00\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'After chap II\', \'sds\', \'dsds\', \'dsd\', \'2024-09-04\', \'2024-09-04 17:07:00\', \'2024-09-04 17:07:00\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Home.php(80): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 17:07:00 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'After chap II\', \'sds\', \'dsds\', \'dsd\', \'2024-09-04\', \'2024-09-04 17:07:00\', \'2024-09-04 17:07:00\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'After chap II\', \'sds\', \'dsds\', \'dsd\', \'2024-09-04\', \'2024-09-04 17:07:00\', \'2024-09-04 17:07:00\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (\'After chap II\', \'sds\', \'dsds\', \'dsd\', \'2024-09-04\', \'2024-09-04 17:07:00\', \'2024-09-04 17:07:00\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `client` (`livre`, `nom`, `adresse`, `tel`, `date_emprunt`, `created_at`, `updated_at`) VALUES (:livre:, :nom:, :adresse:, :tel:, :date_emprunt:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Home.php(80): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 20:38:16 --> ErrorException: Undefined array key "password"
[Method: GET, Route: /]
in APPPATH\Controllers\Home.php on line 110.
 1 APPPATH\Controllers\Home.php(110): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "password"', 'C:\\laragon\\www\\bibliothèque\\app\\Controllers\\Home.php', 110)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->login()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 20:38:51 --> ErrorException: Undefined array key "password"
[Method: GET, Route: /]
in APPPATH\Controllers\Home.php on line 110.
 1 APPPATH\Controllers\Home.php(110): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "password"', 'C:\\laragon\\www\\bibliothèque\\app\\Controllers\\Home.php', 110)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->login()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 20:38:53 --> ErrorException: Undefined array key "password"
[Method: GET, Route: /]
in APPPATH\Controllers\Home.php on line 110.
 1 APPPATH\Controllers\Home.php(110): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "password"', 'C:\\laragon\\www\\bibliothèque\\app\\Controllers\\Home.php', 110)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->login()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 20:39:03 --> ErrorException: Undefined array key "password"
[Method: GET, Route: /]
in APPPATH\Controllers\Home.php on line 110.
 1 APPPATH\Controllers\Home.php(110): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "password"', 'C:\\laragon\\www\\bibliothèque\\app\\Controllers\\Home.php', 110)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->login()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 20:39:17 --> ErrorException: Undefined array key 2
[Method: GET, Route: /]
in APPPATH\Controllers\Home.php on line 110.
 1 APPPATH\Controllers\Home.php(110): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key 2', 'C:\\laragon\\www\\bibliothèque\\app\\Controllers\\Home.php', 110)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->login()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 20:59:58 --> ErrorException: Trying to access array offset on value of type null
[Method: POST, Route: loginclick]
in APPPATH\Controllers\Home.php on line 114.
 1 APPPATH\Controllers\Home.php(114): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\laragon\\www\\bibliothèque\\app\\Controllers\\Home.php', 114)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->loginClick()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 21:00:44 --> ParseError: syntax error, unexpected token "}", expecting ";"
[Method: POST, Route: loginclick]
in APPPATH\Controllers\Home.php on line 118.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\bibliothèque\\app\\Controllers\\Home.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\Home', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 21:26:50 --> ErrorException: Trying to access array offset on value of type null
[Method: POST, Route: loginclick]
in APPPATH\Controllers\Home.php on line 114.
 1 APPPATH\Controllers\Home.php(114): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\laragon\\www\\bibliothèque\\app\\Controllers\\Home.php', 114)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->loginClick()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 21:45:00 --> ErrorException: Trying to access array offset on value of type null
[Method: POST, Route: loginclick]
in APPPATH\Controllers\Home.php on line 114.
 1 APPPATH\Controllers\Home.php(114): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\laragon\\www\\bibliothèque\\app\\Controllers\\Home.php', 114)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->loginClick()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
INFO - 2024-09-04 21:46:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-04 21:46:15 --> ErrorException: Undefined variable $livres
[Method: GET, Route: accueil]
in APPPATH\Views\home.php on line 155.
 1 APPPATH\Views\home.php(155): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $livres', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 155)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(139): view('home')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->accueil()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
INFO - 2024-09-04 21:47:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-04 21:49:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-04 21:52:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-04 22:01:02 --> ParseError: syntax error, unexpected token ";", expecting identifier or variable or "{" or "$"
[Method: GET, Route: liste]
in APPPATH\Controllers\Home.php on line 70.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\bibliothèque\\app\\Controllers\\Home.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\Home', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
INFO - 2024-09-04 22:04:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-04 22:04:39 --> Error: Object of class CodeIgniter\HTTP\RedirectResponse could not be converted to string
[Method: POST, Route: loginclick]
in APPPATH\Controllers\Home.php on line 120.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->loginClick()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
INFO - 2024-09-04 22:05:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-04 22:06:44 --> ErrorException: Undefined variable $user
[Method: GET, Route: home/1]
in APPPATH\Views\home.php on line 143.
 1 APPPATH\Views\home.php(143): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 143)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [...], true)
 5 APPPATH\Controllers\Home.php(72): view('home', [...], [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home('1')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
INFO - 2024-09-04 22:12:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-04 22:12:43 --> ErrorException: Undefined array key "username"
[Method: GET, Route: home/1]
in APPPATH\Views\home.php on line 143.
 1 APPPATH\Views\home.php(143): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "username"', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 143)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(76): view('home', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home('1')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:13:08 --> ErrorException: Undefined variable $data
[Method: GET, Route: home/1]
in APPPATH\Views\home.php on line 143.
 1 APPPATH\Views\home.php(143): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 143)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(76): view('home', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home('1')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:13:10 --> ErrorException: Undefined variable $data
[Method: GET, Route: home/1]
in APPPATH\Views\home.php on line 143.
 1 APPPATH\Views\home.php(143): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 143)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(76): view('home', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home('1')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
INFO - 2024-09-04 22:14:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-04 22:14:36 --> ErrorException: Undefined array key "username"
[Method: GET, Route: home/1]
in APPPATH\Views\home.php on line 143.
 1 APPPATH\Views\home.php(143): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "username"', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 143)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(76): view('home', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home('1')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:15:44 --> ErrorException: Undefined array key "titres"
[Method: GET, Route: home/1]
in APPPATH\Views\home.php on line 143.
 1 APPPATH\Views\home.php(143): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titres"', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 143)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(76): view('home', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home('1')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:15:54 --> ErrorException: Undefined array key "titre"
[Method: GET, Route: home/1]
in APPPATH\Views\home.php on line 143.
 1 APPPATH\Views\home.php(143): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titre"', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 143)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(76): view('home', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home('1')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:16:07 --> ErrorException: Array to string conversion
[Method: GET, Route: home/1]
in APPPATH\Views\home.php on line 143.
 1 APPPATH\Views\home.php(143): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 143)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(76): view('home', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home('1')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:16:32 --> ErrorException: Array to string conversion
[Method: GET, Route: home/1]
in APPPATH\Views\home.php on line 143.
 1 APPPATH\Views\home.php(143): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 143)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(76): view('home', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home('1')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:16:43 --> ErrorException: Undefined array key "id"
[Method: GET, Route: home/1]
in APPPATH\Views\home.php on line 143.
 1 APPPATH\Views\home.php(143): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 143)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(76): view('home', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home('1')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
INFO - 2024-09-04 22:21:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-04 22:22:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-04 22:22:44 --> ArgumentCountError: Too few arguments to function App\Controllers\Home::home(), 0 passed in C:\laragon\www\bibliothèque\system\CodeIgniter.php on line 933 and exactly 1 expected
[Method: GET, Route: home/home]
in APPPATH\Controllers\Home.php on line 66.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:23:22 --> ParseError: syntax error, unexpected token "}", expecting ";"
[Method: GET, Route: home/home]
in APPPATH\Controllers\Home.php on line 81.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\bibliothèque\\app\\Controllers\\Home.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\Home', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:23:23 --> ErrorException: Cannot redeclare App\Controllers\Home::home()
[Method: GET, Route: home/home]
in APPPATH\Controllers\Home.php on line 79.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-09-04 22:23:25 --> ErrorException: Cannot redeclare App\Controllers\Home::home()
[Method: GET, Route: home/home]
in APPPATH\Controllers\Home.php on line 79.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-09-04 22:23:41 --> ErrorException: Undefined variable $user
[Method: GET, Route: home/home]
in APPPATH\Views\home.php on line 143.
 1 APPPATH\Views\home.php(143): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user', 'C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php', 143)
 2 SYSTEMPATH\View\View.php(234): include('C:\\laragon\\www\\bibliothèque\\app\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(80): view('home')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->homme()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
INFO - 2024-09-04 22:25:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-04 22:28:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-04 22:30:55 --> ArgumentCountError: Too few arguments to function App\Controllers\Home::home(), 0 passed in C:\laragon\www\bibliothèque\system\CodeIgniter.php on line 933 and exactly 1 expected
[Method: GET, Route: home/home]
in APPPATH\Controllers\Home.php on line 66.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->home()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
INFO - 2024-09-04 22:32:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-04 22:32:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-04 22:43:11 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: AddClient]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('0000000009', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:46:05 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: AddClient]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('0000000009', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:46:17 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: AddClient]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('0000000009', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:46:24 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: AddClient]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('0000000009', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:49:09 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: AddClient]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Home.php(101): CodeIgniter\Model->update('0000000009', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:52:11 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: AddClient]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Home.php(101): CodeIgniter\Model->update('0000000009', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 22:58:26 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: AddClient]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Home.php(101): CodeIgniter\Model->update('0000000014', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->AddClient()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
CRITICAL - 2024-09-04 23:55:33 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "0000000038&Harry Potter"
[Method: GET, Route: client/RendreLivre/0000000038&Harry%20Potter]
in SYSTEMPATH\Router\Router.php on line 737.
 1 SYSTEMPATH\Router\Router.php(204): CodeIgniter\Router\Router->checkDisallowedChars('client/RendreLivre/0000000038&Harry Potter')
 2 SYSTEMPATH\CodeIgniter.php(834): CodeIgniter\Router\Router->handle('client/RendreLivre/0000000038&Harry Potter')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\laragon\\www\\bibliothèque\\public\\index.php')
